name: rustyserver
services:
    nginx:
        build:
            context: services/sslProxy
        ports:
            - "443:443"
            - "80:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    db:
        image: postgres:14.6
        ports:
            - "5432:5432"
        # TODO: #1182 remove before prod https://github.com/drazisil/mco-server/issues/1008
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "mcos"
    pgadmin:
        image: dpage/pgadmin4:6.18
        # TODO: #1182 remove these before prod https://github.com/drazisil/mco-server/issues/1008
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
            PGADMIN_DEFAULT_PASSWORD: "password"
            PGADMIN_LISTEN_PORT: "80"
            POSTGRES_DB: "mcos"
        ports:
            - "15432:80"
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - db

volumes:
    pgadmin:
