name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake lcov g++ make

      - name: Build and run tests
        run: |
          make clean
          make build

      - name: Generate coverage report
        run: |
          make coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov-report/

      - name: Upload lcov.info
        uses: actions/upload-artifact@v4
        with:
          name: lcov-info
          path: coverage/lcov.info
